version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: YOUR_USERNAME
      POSTGRES_PASSWORD: YOUR_PASSWORD
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: YOUR_EMAIL
      PGADMIN_DEFAULT_PASSWORD: YOUR_PASSWORD
    ports:
      - "5050:80"
    depends_on:
      - db

  webapi:
    build: .
    container_name: dotnet-api
    ports:
      - "5093:5093"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreConnection: "Host=db;Port=5432;Database=test;Username=YOUR_USERNAME;Password=YOUR_PASSWORD"

volumes:
  postgres-data:
